
  Hashing:- Technique which is used in data structure to store & retrieve data effectively.
  Hash Function:- Function which is used to link the data to its index in the hash table.
  Hash Table:- Data structure which is used to store data in the form of key-value pair.
  Hash Collision:- When two different keys are hashed to the same index in the hash table.
  -----------------------------------------------------------------------------------------------------

  Collision Resolution:- Technique which is used to resolve the hash collision.
       For example, if we have a hash table of size 10 and 9 elements, we want to insert the key 15. It will be hashed to index 5 (15 % 10 = 5). If we then insert the key 25, it will also be hashed to index 5 (25 % 10 = 5). In this case, we need to resolve the collision using a collision resolution technique.

             1. Separate Chaining:- Technique which is used to resolve hash collision by storing the collided keys in a linked list at the same index.
             e.g. store the both keys 15 & 25 by the formation of linked list at the index 5 of the hash table.

             Problem with this technique arises if all keys hash to the same index, resulting in a single linked list containing all keys at that index. This degrades search time complexity to O(n).

             Load Factor: total no. of elements in hash table / size of hash table 
             e.g. for above example load factor = 9/10 = 0.9 
-------------------------------------------------------------------------------------

            2. Open Addressing or Closed Hashing:- Technique which is used to resolve hash collision by finding the next available index in the hash table.
              e.g. If we have to insert the key 15, it will be hashed to index 5 (15 % 10 = 5). If we then have to insert the key 25, it will again be hashed to index 5 (25 % 10 = 5). In this case, we solve the collision by finding the next available index in the hash table and inserting the key 25 at that index.
              There are three types of open addressing techniques:
                 a. Linear Probing:- Technique which is used to resolve hash collision by finding the next available index in the hash table in a linear manner.
                   H(key) = (key % table_size + i) % table_size, where i is the number of attempts to find an empty slot.
                    e.g. (Refer to the earlier example with keys 15 and 25) — in linear probing, after a collision at index 5, we search linearly for the next available index to insert the key.

                    ~~~~~primary clustering 
                 b. Quadratic Probing:- Technique which is used to resolve hash collision by finding the next available index in the hash table using a quadratic function.
                   H(key) = (hash(key) + i^2) % table_size, where i is the number of attempts to find an empty slot.
                    e.g. (Refer to the earlier example with keys 15 and 25) — in quadratic probing, after a collision at index 5, we search for the next available index using a quadratic function to insert the key.

                    ~~~~secondary clustering-: follow same pattern of after some attempts to find an empty slot.

                 c. Double Hashing:- Technique which is used to resolve hash collision by finding the next available index in the hash table using a second hash function.
                   H(key) = (Hash1(key) + i* Hash_2(key))% Table_size, where i is the number of attempts to find an empty slot.
                    e.g. (Refer to the earlier example with keys 15 and 25) — in double hashing, after a collision at index 5, we use a second hash function to determine the next available index for insertion.

---------------------------------------------------------------------------------------------------------------------

For String:-
 Hash Function:- Function which is used to link the string to its index in the hash table.It is done by converting the string into an integer(Hash code) and then applying the hash function to that integer(Compression function--mapping).
  1. Hash Code:- Integer value which is generated by converting the string into an integer.
      e.g. for the string "abc", we can generate a hash code by using the formula: hash_code = (s[0] * 31^2 + s[1] * 31^1 + s[2] * 31^0) % table_size, where s[i] is the ASCII value of the character at index i in the string.
  2. Compression Function:- Function which is used to map the hash code to the index in the hash table.



                   
  
             



